---
root: true
plugins:
  - '@typescript-eslint'
  - prettier
  - deprecation
  - import
extends:
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - plugin:import/typescript
rules:
  '@typescript-eslint/interface-name-prefix': 'off'
  '@typescript-eslint/explicit-module-boundary-types': 'off'
  '@typescript-eslint/no-explicit-any': 'off'
  deprecation/deprecation: warn
  import/no-unresolved: error
parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: module
  project: tsconfig.json
settings:
  import/parsers:
    '@typescript-eslint/parser':
      - '.ts'
  import/resolver:
    typescript:
      project: './tsconfig.json'
